author: [DerFlash, twonky4]
database: true
description: Generate basic stats
main: de.cubenation.plugins.cnstats.CnStats
name: CNStats
startup: postworld
url: http://www.cube-nation.de/
version: '${project.version}'

depend:
  - PluginUtils
